package:
  name: nifty
  version: v1.0.10


source:
  path: ..


build:
  number: 1000


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

  host:
#      TODO: update the following req
    - python =3.7.6
#      TODO: update the following req
    - boost-cpp =1.72
    - hdf5 >=1.10
    - numpy >=1.15
    - blosc
    - z5py >=2.0.5
    - vigra
    - bzip2
    - zlib
    - xtensor
    - xtensor-python
    - nlohmann_json

  run:
 #      TODO: update the following req
    - python =3.7.6
    - scikit-image
    - vigra
    - hdf5 >=1.10
    - numpy >=1.15
    - blosc
    - bzip2
    - zlib


test:
  imports:
    - nifty


about:
  home: https://github.com/DerThorsten/nifty
  license: MIT
  summary: Graph-based segmentation algorithms
